#!/bin/bash

NAME="django_boards"
DIR=/home/seegler/git/projects/boards-app-django-fullstack-py/django-boards
USER=seegler
GROUP=seegler
WORKERS=3
BIND=unix:/env/apps/django-boards/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=django-boards.settings
DJANGO_WSGI_MODULE=django-boards.wsgi
LOG_LEVEL=info
LOG_FILE=/env/apps/django-boards/logs/gunicorn.log

cd $DIR

source ../venv/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec ../venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=$LOG_FILE
